In [1]:
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.ensemble import RandomForestClassifier
import numpy as np

n_samples = 100

# generates 2 n_samples random time series with integer values from 0 to 100.
x1 = np.array([np.random.randint(0, 100, 5) for _ in range(n_samples)])
x2 = np.array([np.random.randint(0, 100, 5) for _ in range(n_samples)])

X = np.hstack((x1, x2))


# generates n_samples random binary labels.
y = np.random.randint(0, 2, n_samples)

#Random Forest classifier
clf=RandomForestClassifier(random_state = 42, class_weight="balanced", criterion = 'gini', max_depth = 3, max_features = 'auto', n_estimators = 500)

k_fold = StratifiedKFold(n_splits=10, shuffle=True, random_state=0)

output = cross_validate(clf, X, y, cv=k_fold, scoring = 'roc_auc', return_estimator =True)

In [5]:
print(X[:5])

[[22 43 30 87 76 13 40 54 62 80]
 [54 64 71 92 73 99 61 87 41  2]
 [96 41 52  7 69 72 89 53 86 24]
 [23  5 47 38 57 52 36 34 27  3]
 [89 60 22 88 86  2 41 31 33 69]]


In [6]:
y[:5]

array([1, 0, 0, 1, 0])

In [8]:
output

{'fit_time': array([0.6535418 , 0.6530478 , 0.64880395, 0.64424229, 0.64716959,
        0.64922976, 0.6494329 , 0.6467042 , 0.65425992, 0.6490202 ]),
 'score_time': array([0.06060314, 0.05500627, 0.05407214, 0.05387092, 0.05409122,
        0.05374527, 0.05819893, 0.05465698, 0.05700707, 0.05488276]),
 'estimator': [RandomForestClassifier(class_weight='balanced', max_depth=3, n_estimators=500,
                         random_state=42),
  RandomForestClassifier(class_weight='balanced', max_depth=3, n_estimators=500,
                         random_state=42),
  RandomForestClassifier(class_weight='balanced', max_depth=3, n_estimators=500,
                         random_state=42),
  RandomForestClassifier(class_weight='balanced', max_depth=3, n_estimators=500,
                         random_state=42),
  RandomForestClassifier(class_weight='balanced', max_depth=3, n_estimators=500,
                         random_state=42),
  RandomForestClassifier(class_weight='balanced', max_depth=3, n_